Set-PSFConfig -Module ZeroTrustAssessment -Name 'Logging.Database.IncludeQueryResults' -Value $false -Initialize -Validation bool -Description 'Include the individual results from queries against the internal database in the logs. Significantly increases logsize and includes sensitive data.'
Set-PSFConfig -Module ZeroTrustAssessment -Name 'Logging.InMemoryLog.MinSize' -Value 51200 -Initialize -Validation integer -Description 'The smallest size the in-memory log may be. If it is configured to be less than that, the size will be raised during module import. A large log may impact memory consumption, but will enable better troubleshooting.'
Set-PSFConfig -Module ZeroTrustAssessment -Name 'Graph.DisableCache' -Value $false -Initialize -Validation bool -Description 'Global toggle to disable caching. Caching improves performance of some requests, but potentially consumes a lot of memory, which might lead to swapping and cratering code performance.'
Set-PSFConfig -Module ZeroTrustAssessment -Name 'TabExpansion.TestLimit' -Value 10 -Initialize -Validation integer -Description 'Maximum number of tests offered via tab exansion'
Set-PSFConfig -Module ZeroTrustAssessment -Name 'Export.DependencyWaitLimit' -Value '1d' -Initialize -Validation timespan -Description 'During the export stage of the assessment, how long will a component wait for another export it depends on? If the dependencies are not exported by the timeout, export will fail.'
Set-PSFConfig -Module ZeroTrustAssessment -Name 'Export.SignInLog.MaxSizeBytes' -Value 1073741824 -Initialize -Validation integer -Description 'Maximum size in bytes for sign-in log exports. Defaults to 1GB (1073741824 bytes). When this limit is reached, the export will stop and continue with the next export.'
Set-PSFConfig -Module ZeroTrustAssessment -Name 'ThrottleLimit.Export' -Value 5 -Initialize -Validation integer -Description 'Maximum number of data collectors processed in parallel'
Set-PSFConfig -Module ZeroTrustAssessment -Name 'ThrottleLimit.Tests' -Value 5 -Initialize -Validation integer -Description 'Maximum number of tests processed in parallel'
Set-PSFConfig -Module ZeroTrustAssessment -Name 'Tests.Timeout' -Value '1h' -Initialize -Validation timespan -Description 'Maximum time a single test is allowed to run before it is stopped. Defaults to 1 hour. Set to 0 to disable the timeout. Tests that exceed this limit are recorded as timed out and execution continues with the next test.'
Set-PSFConfig -Module ZeroTrustAssessment -Name 'Tests.UnlicensedAction' -Value 'Skip' -Initialize -Validation string -Description 'What to do when a test requires a license the tenant does not have (e.g. Entra ID P2). Skip = silently skip the test (default). Warn = mark the test as failed with a license warning in the report.'

# ── Connection settings ──────────────────────────────────────────────────────
Set-PSFConfig -Module ZeroTrustAssessment -Name 'Connection.UseTokenCache' -Value $true -Initialize -Validation bool -Description 'Cache authentication tokens to disk so they persist across PowerShell sessions. Avoids repeated sign-in prompts when re-running the assessment. Set to $false to require fresh authentication each time (tokens scoped to process only).'
Set-PSFConfig -Module ZeroTrustAssessment -Name 'Connection.UseDeviceCode' -Value $false -Initialize -Validation bool -Description 'Use device code flow for authentication. Auto-enabled in Codespaces, dev containers, and headless environments. Set to $true to always use device code regardless of environment.'
Set-PSFConfig -Module ZeroTrustAssessment -Name 'Connection.DeviceCodeTimeout' -Value 30 -Initialize -Validation integer -Description 'Seconds to wait before auto-continuing with device code authentication. During this window the user can press [S] to skip the service. Set to 0 to disable the skip prompt and authenticate immediately.'
Set-PSFConfig -Module ZeroTrustAssessment -Name 'Connection.Environment' -Value 'Global' -Initialize -Validation string -Description 'The cloud environment to connect to. Supported values: Global, China, Germany, USGov, USGovDoD.'
Set-PSFConfig -Module ZeroTrustAssessment -Name 'Connection.TenantId' -Value '' -Initialize -Validation string -Description 'Default tenant ID for connections. When set, Connect-ZtAssessment will use this tenant without requiring the -TenantId parameter.'

# ── Assessment behavior ──────────────────────────────────────────────────
Set-PSFConfig -Module ZeroTrustAssessment -Name 'Assessment.SkipGlobalSecureAccess' -Value $false -Initialize -Validation bool -Description 'Skip all Global Secure Access tests regardless of tenant configuration. Set to $true if you know the tenant does not use GSA and want to avoid the API call. When $false (default), GSA tests are automatically skipped if no forwarding profiles are enabled.'
Set-PSFConfig -Module ZeroTrustAssessment -Name 'Connection.ClientId' -Value '' -Initialize -Validation string -Description 'Default application (client) ID for connections. When set, Connect-ZtAssessment will use this app registration without requiring the -ClientId parameter. Required for service principal and managed identity authentication.'

# ── DuckDB settings ───────────────────────────────────────────────────────────
Set-PSFConfig -Module ZeroTrustAssessment -Name 'DuckDB.Version' -Value 'v1.1.1' -Initialize -Validation string -Description 'DuckDB native library version tag (e.g. v1.1.1). Used by Install-DuckDbNativeLibrary to download the correct release from GitHub. Must match the managed .NET bindings (DuckDB.NET.*.dll) shipped in lib/.'
Set-PSFConfig -Module ZeroTrustAssessment -Name 'DuckDB.ReleaseBaseUrl' -Value 'https://github.com/duckdb/duckdb/releases/download' -Initialize -Validation string -Description 'Base URL for DuckDB native library releases. The full download URL is assembled as: {ReleaseBaseUrl}/{Version}/{platform-zip}. Override for air-gapped or mirrored environments.'
