# ── Module-wide constants ─────────────────────────────────────────────────────
# Canonical file and directory names used across the module.
# Always reference these variables instead of hardcoding the strings.

# The HTML report filename generated by Invoke-ZtAssessment.
$script:ZtReportFileName = 'ZeroTrustAssessmentReport.html'

# The JSON report filename inside the export directory.
$script:ZtReportJsonFileName = 'ZeroTrustAssessmentReport.json'

# The subdirectory under the report path that holds exported data.
$script:ZtExportDirName = 'zt-export'

# The per-assessment configuration file inside the export directory.
$script:ZtConfigFileName = 'ztConfig.json'

# The subdirectory under the export path that holds the DuckDB database.
$script:ZtDbDirName = 'db'

# The DuckDB database filename.
$script:ZtDbFileName = 'zt.db'

# Default output path for assessment reports.
$script:ZtDefaultReportPath = './ZeroTrustReport'

# Default port range for the HTTP server used to serve reports in containers.
$script:ZtHttpPortStart = 8080
$script:ZtHttpPortEnd = 8089
